# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'MyQrScanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SimpleQRCode', '~> 0.6'
    pod 'QRCoder', '~> 1.1'

  # Pods for MyQrScanner
end
